### ISSUE TITLE
Error when build library.

### ISSUE THREAD

**Issue by DimonDeveloper** [ararog/Unrar4iOS#13]
How to fix it?
Framework: Cleaning framework...
Framework: Setting up directories...
Framework: Creating symlinks...
Framework: Creating library...
fatal error: lipo: can't open input file: /Users/dmitryvlasenko/Library/Developer/Xcode/DerivedData/Unrar4iOS-ffptbadnmkvcomfmropxmeihaxhl/Build/Products/Debug-iphoneos/libUnrar4iOS.a (No such file or directory)
Framework: Copying assets into current version...
Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure

**Comment by augard** [comment]
Set target to iOS device and follow installation part in readme
