### ISSUE TITLE
Does not work on device build for iOS 7

### ISSUE THREAD

**Issue by jjxtra** [ararog/Unrar4iOS#17]
Framework does not link properly on Xcode 7 device builds. I drag framework into my project, do a build to device and it says it can't find the framework.

**Comment by elbertv** [comment]
jjxtra how you solve this issue?

**Comment by jjxtra** [comment]
I just made iOS 8 my minimum target

**Comment by jjxtra** [comment]
Doesn't seem to be an issue anymore

**Comment by elbertv** [comment]
By now I have 4 days trying to install (with no success) but always has the same message, 
ld: framework not found Unrar4iOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)

And is loaded in "link binary with libraries". This seems to be the best and most used library for rar files, but can loaded. Can you please guide me to the answer of my error???
