### ISSUE TITLE
port isnt working on the device with IOS 4.2 kindly help !!!

### ISSUE THREAD

**Issue by gops19** [ararog/Unrar4iOS#2]
Hi the framwork works fine on the simulator but when you running off the device , it gives the following error
2011-05-01 13:11:51.657 UnrarExample[6608:307] -[Unrar4iOS unrarOpenFile:]: unrecognized selector sent to instance 0x1690a0
2011-05-01 13:11:51.671 UnrarExample[6608:307] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[Unrar4iOS unrarOpenFile:]: unrecognized selector sent to instance 0x1690a0'
**\* Call stack at first throw:
(
    0   CoreFoundation                      0x3587a987 **exceptionPreprocess + 114
    1   libobjc.A.dylib                     0x34a8249d objc_exception_throw + 24
    2   CoreFoundation                      0x3587c133 -[NSObject(NSObject) doesNotRecognizeSelector:] + 102
    3   CoreFoundation                      0x35823aa9 ___forwarding_** + 508
    4   CoreFoundation                      0x35823860 _CF_forwarding_prep_0 + 48
    5   UnrarExample                        0x00003107 -[UnrarExampleViewController decompress:] + 130
    6   CoreFoundation                      0x35821fed -[NSObject(NSObject) performSelector:withObject:withObject:] + 24
    7   UIKit                               0x341c84ad -[UIApplication sendAction:to:from:forEvent:] + 84
    8   UIKit                               0x341c844d -[UIApplication sendAction:toTarget:fromSender:forEvent:] + 32
    9   UIKit                               0x341c841f -[UIControl sendAction:to:forEvent:] + 38
    10  UIKit                               0x341c8171 -[UIControl(Internal) _sendActionsForEvents:withEvent:] + 356
    11  UIKit                               0x341c7e1f -[UIControl touchesBegan:withEvent:] + 186
    12  UIKit                               0x341be311 -[UIWindow _sendTouchesForEvent:] + 300
    13  UIKit                               0x341bdccf -[UIWindow sendEvent:] + 262
    14  UIKit                               0x341a8fc7 -[UIApplication sendEvent:] + 298
    15  UIKit                               0x341a8907 _UIApplicationHandleEvent + 5090
    16  GraphicsServices                    0x320c8f03 PurpleEventCallback + 666
    17  CoreFoundation                      0x3580f6ff __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 26
    18  CoreFoundation                      0x3580f6c3 __CFRunLoopDoSource1 + 166
    19  CoreFoundation                      0x35801f7d __CFRunLoopRun + 520
    20  CoreFoundation                      0x35801c87 CFRunLoopRunSpecific + 230
    21  CoreFoundation                      0x35801b8f CFRunLoopRunInMode + 58
    22  GraphicsServices                    0x320c84ab GSEventRunModal + 114
    23  GraphicsServices                    0x320c8557 GSEventRun + 62
    24  UIKit                               0x341dc329 -[UIApplication _run] + 412
    25  UIKit                               0x341d9e93 UIApplicationMain + 670
    26  UnrarExample                        0x00002d8b main + 70
    27  UnrarExample                        0x00002d40 start + 40

**Comment by ararog** [comment]
Please set the deployment target to 3.0

**Comment by ararog** [comment]
I set the deployment target of both projects (Unrar4iOS and UnrarExample) to 3.0 and tested in a iPhone 3G device with iOS 4.2.1, the example application worked as expected.
