### ISSUE TITLE
Don't use exceptions for error handling

### ISSUE THREAD

**Issue by augard** [ararog/Unrar4iOS#9]
For compatibility with ARC code: 7.6. Exceptions By default in Objective C, ARC is not exception-safe for normal releases…

Rationale: the standard Cocoa convention is that exceptions signal programmer error and are not intended to be recovered from. Making code exceptions-safe by default would impose severe runtime and code size penalties on code that typically does not actually care about exceptions safety. Therefore, ARC-generated code leaks by default on exceptions, which is just fine if the process is going to be immediately terminated anyway. Programs which do care about recovering from exceptions should enable the option.

**Comment by ararog** [comment]
Feel free to submit a PR.

**Comment by ararog** [comment]
I believe your latest PR fixed this, please let me know if not.
